var lname;
lname = "Santosh";
var newname = lname.toUpperCase();
console.log(newname);
var age;
age = 25;
age = 25.5;
var dob = "25";
var result = parseInt(dob);
var isValid = false;
console.log(isValid);
var empList;
empList = ["hello", "good morning", "wasa"];
var numList;
numList = [1, 2, 3, 4, 5];
var results = numList.filter(function (num) { return num > 2; });
var emp = empList.find(function (emp) { return emp === "hello"; });
var sum = numList.reduce(function (acc, num) { return acc + num; });
console.log(results);
console.log(emp);
console.log(sum);
